version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - BLOCKCHAIN_ENDPOINT=${BLOCKCHAIN_ENDPOINT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_PORT=${DB_PORT}
      - S3_ACCESS_KEY=${S3_ACCESS_KEY}
      - S3_SECRET_KEY=${S3_SECRET_KEY}
      - FIREBASE_API_KEY=${FIREBASE_API_KEY}
      - PRIVATE_KEY=${PRIVATE_KEY}
      - INFURA_PROJECT_ID=${INFURA_PROJECT_ID}
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    volumes:
      - .:/app
      - /app/node_modules

  blockchain:
    image: trufflesuite/ganache-cli
    ports:
      - "8545:8545"

  websocket:
    build: .
    ports:
      - "8080:8080"
    command: node blockchain/src/websocket.js
    environment:
      - NODE_ENV=production
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
